name: Hereafter
options:
  bundleIdPrefix: com.loudlabs
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"  # iPhone only
    INFOPLIST_FILE: Hereafter/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.loudlabs.hereafter
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  Hereafter:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Hereafter
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: Hereafter/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.loudlabs.hereafter
        CODE_SIGN_ENTITLEMENTS: ""
        GENERATE_INFOPLIST_FILE: false
    info:
      path: Hereafter/Resources/Info.plist
    entitlements:
      path: Hereafter/Hereafter.entitlements
